#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 26 14:24:51 2018

@author: joseantoniob.c.laranjeira
"""

import json

with open( "controledeestoque.json", "r") as estoque:
    Estoque=json.loads(estoque.read())


Estoque={}
print("0-sair")
print("1-adicionar_item") 
print("2-remover_item")
print("3-alterar_item")
print("4-imprimir_estoque")

Escolha=int(input("Faca sua escolha: "))
while Escolha!=0:
#Escolha 1    
    if Escolha == 1:
      nome= input("Nome do produto: ")
      if nome not in Estoque :
          quantidade=int(input("quantidadde inicial: "))
          valor=float(input("Valor do produto:  "))
          if valor<0:
              print("Valor nao pode ser negativo")
              valor=float(input("Valor do produto:  "))
          while quantidade < 0:
              print('Quantidade inicial não pode ser negativa')
              quantidade=int(input("quantidadde inicial: "))
          Estoque[nome]={'quantidade':quantidade,'valor':valor}
      else:
          print ("Produto ja cadastrado")
      
#Escolha 2          
    if Escolha==2:
        nome=input("Nome do produto a ser removido:  ")
        if nome in Estoque:
            del Estoque[nome]
            print(Estoque)
            print ("Produto removido")
        else:
            print ("Elemento nao encontrado")
        
#Escolha 3   
    if Escolha==3:
        nome= input("Nome do produto: ")
        if nome in Estoque:
          Nquantidade=int(input("Deseja alterar a quantidade? (Sim: digite 1 / Nao: digite 2)  "))
          if Nquantidade==1:
              novaquantidade=int(input("Nova quantidade: "))
              Estoque[nome]['quantidade']+=novaquantidade
              nvalor=int(input("Deseja alterar o valor? (Sim: digite 1 / Nao: digite 2)  "))
              if nvalor==1:
               novovalor=int(input("Novo Valor:  "))
               Estoque[nome]['valor']=novovalor
          elif Nquantidade==2:
               novovalor=int(input("Novo Valor:  "))
               Estoque[nome]['valor']=novovalor
              
            
          print("Novo estoque de {0} é {1},e o valor é {2} reais:".format(nome,Estoque[nome]['quantidade'],Estoque[nome]['valor']))
        else:
            print("Elemento nao encontrado")
        
#Escolha 4
    if Escolha==4:
        vmonetario=0
        for nome in Estoque:
            print("{0}:{1} unidades - valor: {2}".format(nome,Estoque[nome]['quantidade'],Estoque[nome]['valor']))
            valormonetario= Estoque[nome]['quantidade']*Estoque[nome]['valor']
            vmonetario+=valormonetario
        print("O valor total do estoque é {0} Reais ".format(vmonetario))
        


    print("   ")
    print("0-sair")
    print("1-adicionar_item") 
    print("2-remover_item")
    print("3-alterar_item")
    print("4-imprimir_estoque")   
    Escolha=int(input("Faca sua escolha:"))
print("Ate mais")

with open ("controledeestoque","w") as fim:
    Estoque= json.dumps(Estoque, sort_keys= True, indent=4)
    fim.write(Estoque)